// <auto-generated />
using FIRST_DOTNET_PROEJCT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIRST_DOTNET_PROEJCT.Migrations
{
    [DbContext(typeof(MyAppContextDb))]
    [Migration("20241225150844_AddCategorieTableTo")]
    partial class AddCategorieTableTo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIRST_DOTNET_PROEJCT.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdreAffichage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobile",
                            OrdreAffichage = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ordinateur",
                            OrdreAffichage = "2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Périphériques",
                            OrdreAffichage = "3"
                        });
                });

            modelBuilder.Entity("FIRST_DOTNET_PROEJCT.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrixProduit")
                        .HasColumnType("int");

                    b.Property<int>("categorieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 123456789,
                            Description = "iPhone 14 Pro. Avec un appareil photo principal de 48 MP pour capturer des détails époustouflants.DynamicIsland et l'écran toujours activé, qui offrent une toute nouvelle expérience sur iPhone",
                            Name = "Iphone 14",
                            PrixProduit = 10000,
                            categorieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = 546456789,
                            Description = "Toutes les fonctions de base,désormais faciles à utiliser.Imprimez,numérisez et copiezles documents quotidiens,et profitez d’une connexion simple et sans fil",
                            Name = "Imprimante hp deskjet 2710",
                            PrixProduit = 5000,
                            categorieId = 2
                        });
                });

            modelBuilder.Entity("FIRST_DOTNET_PROEJCT.Models.Produit", b =>
                {
                    b.HasOne("FIRST_DOTNET_PROEJCT.Models.Categorie", "categorie")
                        .WithMany()
                        .HasForeignKey("categorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
